edit update delete
StoryEdutech/study_repo pull request #29
Opened 2023-05-14 06:03 UTC by mokupon

# 内容

### 言語／フレームワーク
- Laravel
- React

### 勉強時間（※大体でOK）
4時間

### 勉強内容
- 編集,削除,更新機能の作成をしました。
- 投稿一覧ページに対して、投稿者の名前を表示しました。
最低限のcrudの作成は完了しましたが、modelの扱いがうまくできてないので、もう少し模索したいと思ってます。
(モデルのメリットを活かしきれてないきがしてる)

### 次勉強するもの
- phpでのオブジェクトの扱いについてを学習(laravelのコード理解を深めるため)
- 認証あたりの充実化
- typescript・nextjsでのコード記載(次ではないが、長期的には)

# 感想
### 有用と思ったもの・意外だったもの
- モデル内にsqlを書くことで、コントローラーのコード量を減らせること。

### 苦戦したもの
- 投稿一覧に対して、投稿者の名前を表示させたこと。
joinでテーブルをくっつけて投稿者名を取得したが、もっと良い方法があるのでは、、。と思っています。
(モデルのuserメソッドを使うなりして)

### 楽しかったもの（※任意）
- ソフトデリートで、完全に削除されないという喜びを知った。
(コベツバの全DBにやるのは流石に違うのかな、？重くなりそう)

2023-05-14 15:42 UTC, enes1004 requested changes

2023-05-14 15:42 UTC, enes1004 commented on takei/blog/app/Models/Post.php
> +
このやり方、だめです。

やりたいのはおそらく、

`Post::all()->with('user')`

です。集計以外では、Join/selectはほぼ禁止です。使い勝ってが悪いし、編集しにくいし、読みにくいので。

2023-05-14 15:42 UTC, enes1004 commented on takei/blog/resources/js/Pages/Post/Edit.jsx
> +        setData(event.target.name, event.target.type === 'checkbox' ? event.target.checked : event.target.value);
checkboxがないのになぜこういう記載がある？？？どこかからのパクリ？？

2023-05-14 15:42 UTC, enes1004 commented on takei/blog/routes/web.php
>      ->names([
~基本、ルートは複数形使わない方がいいです。~ Laravelの公式資料にも「photos」があったので、OKかもしれません。index以外は単体のものを扱うルートなので、あまり気持ちよいとは言えませんが

後、最初の「/」も不要です


また、namesへのこだわりがあまり分からないです。Resourceの基本設定とまったく一緒なので、記載が無意味な気がします。

https://laravel.com/docs/10.x/controllers#actions-handled-by-resource-controller

2023-05-15 00:22 UTC, mokupon commented on takei/blog/resources/js/Pages/Post/Edit.jsx
> +        setData(event.target.name, event.target.type === 'checkbox' ? event.target.checked : event.target.value);
laravel breezeにて入っていた、
[resources/js/Pages/Auth/Register.jsx](https://github.com/StoryEdutech/study_repo/blob/96a987881c1aed3284ee199169adacd9f917ec60/takei/blog/resources/js/Pages/Auth/Register.jsx#L23-L25)
からパクってきたものです。

同じ処理のため、helperとして用意するべきだったということであっているでしょうか、？

2023-05-15 00:49 UTC, mokupon commented on takei/blog/app/Models/Post.php
> +
ありがとうございます、。
やりたかったのはそちらでした。
修正済です。

2023-05-15 01:19 UTC, enes1004 commented on takei/blog/resources/js/Pages/Post/Edit.jsx
> +        setData(event.target.name, event.target.type === 'checkbox' ? event.target.checked : event.target.value);
helperにするほどのものじゃないと思います。理想は消すことです。パクるのはいいだが、何をしているかを把握するためにも、他者が見たときのノイズにならないようにも、不要な部分を消すべき

2023-05-15 01:55 UTC, closed without merging