Takei blog
StoryEdutech/study_repo pull request #53
Opened 2023-05-18 05:01 UTC by mokupon

# 内容

### 言語／フレームワーク
- Laravel
- React

### 勉強時間（※大体でOK）

合計◯◯時間

### 勉強内容

例：Controller作りました・データベースに接続を果たせました

- 

### 次勉強するもの
- 

# 感想
### 有用と思ったもの・意外だったもの
- 

### 苦戦したもの
- 

### 楽しかったもの（※任意）
-

2023-05-18 07:30 UTC, mokupon commented
@zvvlj0219 
test

2023-05-18 07:30 UTC, mokupon commented
@mokupon 
自分

2023-05-18 10:24 UTC, enes1004 requested changes

2023-05-18 10:24 UTC, enes1004 commented on takei/blog/resources/js/Pages/Posts/Index.jsx
> +                                {/* <th>コンテンツ</th> */}
デッドコード、消す方向でお願いします

2023-05-18 10:24 UTC, enes1004 commented on takei/blog/resources/js/Pages/Posts/Index.jsx
> +                                        {/* <td className="border px-4 py-2">
デッドコード、消す方向で

2023-05-28 05:22 UTC, mokupon commented
@enes1004 
お手好きの際にこちらのFBに対してのコメントの確認をお願いいたします。

2023-05-28 12:45 UTC, enes1004 requested changes
前のレビューの半分しか修正されてない気がします。編集するか、そのまま残すなら訳を書いてほしいです

2023-05-28 12:45 UTC, enes1004 commented on takei/blog/resources/js/Pages/Posts/Index.jsx
> +                                {/* <th>コンテンツ</th> */}
@mokupon 

🚀 ありますが、ここ変わってない気がします

2023-05-29 05:27 UTC, mokupon commented
@enes1004 
> 前のレビューの指摘の半分しか修正されてない気がします。編集するか、そのまま残すなら訳を書いてほしいです

大変申し訳ございません。編集漏れがありました。
編集をして、再度レビュー依頼を出させていただきました。

2023-05-29 06:59 UTC, enes1004 commented on takei/blog/resources/js/Pages/Posts/Show.jsx
> +export default function Show(props) {
@mokupon 

これだけ解決してないので確認を

2023-05-29 07:04 UTC, mokupon commented on takei/blog/resources/js/Pages/Posts/Show.jsx
> +export default function Show(props) {
@enes1004

命名、広すぎる。他のところで使う時やデバッグで困る。

こちら、Show.jsxやIndex.jsx等は確かに横断的なファイル名で、治すべきかもですが、
リソースコントローラが使えなくなるという懸念もあります。

リソースコントローラを用いたほうが、コードの可読性があがり、結果的にデバッグも容易というイメージですが、
PostOne　/　PostShowPage等を用いたほうがよいでしょうか、？

2023-05-29 07:07 UTC, enes1004 commented on takei/blog/resources/js/Pages/Posts/Show.jsx
> +export default function Show(props) {
こちら誤認です。
renderで入れているパスも同時に変更すればいけます（なぜかリンクがとれなかったので、コード部分を記載してます）
```
        return Inertia::render('Posts/Show',['post' => $post]);
```

2023-05-30 01:27 UTC, mokupon commented on takei/blog/resources/js/Pages/Posts/Show.jsx
> +export default function Show(props) {
@enes1004 
[こちらのコミット](https://github.com/StoryEdutech/study_repo/pull/53/commits/5fe12aa669d776a869d8ced7ab70406b3f8271e0)にて、命名変更済みです。

2023-05-30 02:28 UTC, enes1004 commented on takei/blog/resources/js/Pages/Posts/Show.jsx
> +export default function Show(props) {
残念ながら、済みじゃないです。

2023-05-30 03:06 UTC, mokupon commented on takei/blog/resources/js/Pages/Posts/Show.jsx
> +export default function Show(props) {
@enes1004 
こちら、Inertia::render内のShowというのも、PostShowにするべきという認識であっているでしょうか、?
(createやeditも同じように対応)

2023-05-30 03:08 UTC, enes1004 commented on takei/blog/resources/js/Pages/Posts/Show.jsx
> +export default function Show(props) {
> こちら、Inertia::render内のShowというのも、PostShowにするべきという認識であっているでしょうか、?
> (createやeditも同じように対応)
> 

説明している対応と例に出している対応が違ってます。なので、あっているかどうか分からないです。

2023-05-30 03:10 UTC, enes1004 commented on takei/blog/resources/js/Pages/Posts/Show.jsx
> +export default function Show(props) {
createやeditにおいて、Inertia::renderを変えてないでしう。
```
        return Inertia::render('Posts/Create');
```

2023-05-30 11:57 UTC, mokupon commented on takei/blog/resources/js/Pages/Posts/Show.jsx
> +export default function Show(props) {
@enes1004 
大変申し訳ございません。showのコンポーネント名の修正が漏れていて、修正済みです。
[編集箇所](https://github.com/StoryEdutech/study_repo/blob/881323c084262828cb19ae3ea20a9447ef32f6d3/takei/blog/resources/js/Pages/Posts/Show.jsx#L18)

2023-05-30 12:01 UTC, mokupon commented on takei/blog/resources/js/Pages/Posts/Show.jsx
> +export default function Show(props) {
※この武井のブランチにて、過去のコミットに戻りたいと思い、force-pushをしていたため、履歴が汚くなっています。
(こちらでは影響がないのでforce-pushをしてましたが、本サイト等では相談無しでおこないません)

2023-05-31 07:53 UTC, enes1004 approved these changes
指摘された変更の修正出来ているのでマージOKです！

2023-05-31 09:32 UTC, merged