投稿詳細ページ　コメント一覧/投稿
StoryEdutech/study_repo pull request #56
Opened 2023-05-26 05:25 UTC by zvvlj0219

# 内容

### 言語／フレームワーク
- Laravel

### 勉強時間（※大体でOK）

合計5時間

### 勉強内容

例：Controller作りました・データベースに接続を果たせました

- 投稿へのコメントを一覧表示
- コメントを新しく投稿する機能

### 次勉強するもの
- ページネーション #52 
- Policy

# 感想
### 有用と思ったもの・意外だったもの
- load()によるデータ取得ではidを取得できること

### 苦戦したもの
- なし

### 楽しかったもの（※任意）
- 認可を意識しはじめる

2023-05-26 05:57 UTC, enes1004 requested changes
Controller/Modelの扱いは結構いい感じになってきてます。一部無駄の多い部分もありますが、後慣れるだけ、というレベルです。

ちなみに

- Blade
- Model/Controller

それぞれでかかった時間の目安はどうでしょうか？

Bladeが慣れてないから結構時間かかって、5時間となったのか、Model/Controllerの試行錯誤・デバッグが多かったのかを知りたいので。

2023-05-26 05:57 UTC, enes1004 commented on kinoshita/laravel-study/miniblog/app/Http/Controllers/PostController.php
> +        $comments = Comment::with('user')->where('post_id', $post->id)->get();
リレーション使って欲しいです。(withがダメかもしれない。その場合代わりにloadでいけるはずです。)

```suggestion
        $comments = $post->comments()->with('user')->get();
```

2023-05-26 05:57 UTC, enes1004 commented on kinoshita/laravel-study/miniblog/app/Http/Controllers/DashboardController.php
> +        ]);
無駄のコード多いので、以下のどっちかにしてほしいです

```suggestion
        $show_comment_btn = true;

        return view('dashboard', compact(["all_posts", "show_comment_btn"]) );
```

```suggestion
        return view('dashboard', [
            "all_posts" => $all_posts,
            "show_comment_btn" => true
        ]);
```

※Debugbarをなくす場合、

- `$all_posts=Post::with(['user', 'comments'])->get();`もなくして
- `"all_posts" => Post::with(['user', 'comments'])->get(),`にする

方が、読みやすいです。

2023-05-26 05:57 UTC, enes1004 commented on kinoshita/laravel-study/miniblog/app/Http/Controllers/PostController.php
> +        ]);
DashboardControllerのコメントと同じくです

2023-05-26 05:57 UTC, enes1004 commented on kinoshita/laravel-study/miniblog/resources/views/components/blog.blade.php
> +    @if(env("APP_ENV") == "local")
Debug方針としてAPP_ENVを使うのはGoodです！

ただ、こういうデバッグの数が増えすぎたらファイルが見にくくなるので、用済みなら消す、でお願いします（勉強用なので、消す/消さないは任せます。）

実際の開発では、ローカルだけなら出来るだけ先頭にdd()を入れて、確認したらすぐ外す、がベストです。
```
{{ dd( $post ) }}
```

- dd()を入れたらそれ以降の発行が止まって、綺麗な形式で変数の内容が表示される
- できるだけ先頭にすることで、ブラウザーで表示されるページ内でも上になりやすく、「実際表示された時、ページの下にあって、消し忘れた」というのは発生しにくい。

2023-05-26 05:57 UTC, enes1004 commented on kinoshita/laravel-study/miniblog/routes/web.php
> +
Resource系がシンプルで、数増えすぎるのも予想されるので、実は、Laravelがこういうのも提供してます！("resources"の複数形の"s"に注意)
```
Route::resources([
    'photos' => PhotoController::class,
    'posts' => PostController::class,
]);
```
ただ、middlewareが違う場合、ややこしそうなので、一旦編集しなくてOkです！

2023-05-28 03:15 UTC, zvvlj0219 commented on kinoshita/laravel-study/miniblog/app/Http/Controllers/DashboardController.php
> +        ]);
DebagBarは一旦残して、compactを使いました  

```
  public function index()
    {
        $all_posts = Post::with(['user', 'comments'])->get();

        Debugbar::info($all_posts);

        $show_comment_btn = true;

        return view('dashboard', compact(['all_posts', 'show_comment_btn']));
    }

```

2023-05-28 04:33 UTC, zvvlj0219 commented on kinoshita/laravel-study/miniblog/app/Http/Controllers/PostController.php
> +        $comments = Comment::with('user')->where('post_id', $post->id)->get();
動的プロパティとリレーションオブジェクトの違いがよくわかってなかったので、調べてsuggested changeの内容で修正しました
https://qiita.com/179Bell/items/7b4f991816f63946e738

2023-05-28 04:34 UTC, zvvlj0219 commented
## ■修正後レビュー依頼

### やったこと
- コントローラで値を返すときに、compactを使いコード量を減らす
- 動的プロパティとリレーションオブジェクトを理解

2023-05-28 04:38 UTC, zvvlj0219 commented
> ちなみに
> 
> Blade
> Model/Controller
> それぞれでかかった時間の目安はどうでしょうか？
> 
> Bladeが慣れてないから結構時間かかって、5時間となったのか、Model/Controllerの試行錯誤・デバッグが多かったのかを知りたいので。

bladeが3割、controllerが7割て感じです。
controllerでの試行錯誤が多いです

2023-05-29 03:02 UTC, enes1004 requested changes
マージOKです！

一部任意のアドバイスは見返しする可能性を考慮して、Resolveせずにおいておいてます

2023-05-29 03:02 UTC, enes1004 approved these changes

2023-05-29 05:51 UTC, merged