【木下】ページネーションを加える
StoryEdutech/study_repo pull request #57
Opened 2023-05-29 06:11 UTC by zvvlj0219

# 内容

### 言語／フレームワーク
- Laravel

### 勉強時間（※大体でOK）

合計2時間 
　ページネーション自体は、30分程度
　リレーションのデバッグ　1時間３０分

### 勉強内容

例：Controller作りました・データベースに接続を果たせました

- ページネーションを加える

### 次勉強するもの
- Policyを使って認可をする

# 感想
### 有用と思ったもの・意外だったもの
- ページャーがlaravelにデフォルトとしてある機能と知り驚きました。デザインもtailwindとかサードパーティのツールで簡単にカスタマイズできるところ

### 苦戦したもの
- リレーションで苦戦中（調べたりします）

### 楽しかったもの（※任意）
- なし

2023-05-29 06:41 UTC, enes1004 requested changes
コード自体に大きな問題なし。

ただ、リレーションのDebugに1時間半かかるのは気になりました。

- IDEの補助を出来るだけ発展させる。それでいろんなことが安全になる
- どんなに発展させても、限界があるため、信用できないこともある。
- 長くデバッグする前に、「IDEがおかしいのでは？」という疑問があれば（多分、今回もあったと思う）、まずローカル環境で関わる部分を発行・表示させて、コードが動いているかを確認してからデバッグした方がいいです。

でいいと思います。

2023-05-29 06:41 UTC, enes1004 commented on kinoshita/laravel-study/miniblog/app/Http/Controllers/PostController.php
> +        // Undefined method 'posts'.
今日共有した、propertyをのこしたら出てこなくなるかもしれません。
https://zenn.dev/ad5/articles/8133b2a2a4ea99

記者曰く出来るようです。
https://zenn.dev/ad5/articles/8133b2a2a4ea99#%E3%83%AA%E3%83%AC%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%82%82%E8%AA%8D%E8%AD%98%E3%81%95%E3%81%9B%E3%82%8B

2023-05-29 06:41 UTC, enes1004 commented on kinoshita/laravel-study/miniblog/app/Http/Controllers/DashboardController.php
> +        $sort = $request->sort;
これは何？viewで返してないけど大丈夫？

名前から思うにはasc/descで順番替えをしたい、というものだと思いますが。まだWIPの場合、この記載もPushする内容に入れない、がベストです。

2023-05-29 06:41 UTC, enes1004 commented on kinoshita/laravel-study/miniblog/app/Http/Controllers/DashboardController.php
【Better・任意】
面倒くさいのは分かりますが、命名を変えた方がいいかもしれません。（早く気づかず申し訳ない）

ユーザーの投稿のみになったら$user_postsなどが適切ですが、絞る条件がない場合、$postsなどがわかりやすい・無難です。「all」を付ける場合は、「例外的にここだけ全部のデータをとっている」、と強く主張したい場合で大丈夫です。

例えば、

- ある複数の記者がいるブログがある
-トップページは記者毎最新の投稿だけを見せるため、全部の投稿を表示させることがない
- 一方、1万目・2万目の投稿を目立てる仕様がある

こうなったときに、1万目の投稿を全部投稿から計算するため、$all_postsは適切、となります。

ただ、今でもそこまで分かりにくくないので、任意としておきます。

2023-05-30 05:52 UTC, zvvlj0219 commented on kinoshita/laravel-study/miniblog/app/Http/Controllers/DashboardController.php
> +        $sort = $request->sort;
自分がpaginationの実装で調べた記事にて、ページの番号を表示したいときは、おまじないとして必要として書かれていました。
<< 1 | 2| 3 | >>　←こういうのです
 
が、他の記事も見たり、デバッグしたりして、今回はいらないことが分かりました。（もうちょっとよく見ればよかったです）

この行は削除します。

2023-05-30 05:55 UTC, zvvlj0219 commented on kinoshita/laravel-study/miniblog/app/Http/Controllers/DashboardController.php
allなど、何かしらの情報を名前に込めるべきかと思い、all_postsとしていました。
とくに意味もなく、名前に情報を付与するよりは、１つの単語の方が分かりやすいということを理解しました。

postsに修正しました。

2023-05-30 06:06 UTC, enes1004 commented on kinoshita/laravel-study/miniblog/app/Http/Controllers/DashboardController.php
> +        $sort = $request->sort;
私も分からなかった。links()で足りるはずです。

これの代替かな :thinking: 
https://readouble.com/laravel/8.x/ja/pagination.html#appending-query-string-values

まあ、一旦削除でOKです。

2023-05-30 06:49 UTC, zvvlj0219 commented on kinoshita/laravel-study/miniblog/app/Http/Controllers/PostController.php
> +        // Undefined method 'posts'.
■やったこと
記事の通り、プロパティを書きました。

■結果
postインスタンス、commentインスタンスはtab補完ができるようになりました。

userインスタンスは、
controller内で新しくnewしたものなら、tab補完が聞きました。が、auth()->user()のインスタンスにはなぜか聞きませんでした。

■対処
自分がvscodeに入れている「php Intelephense」という拡張機能によるものでしたので、「未定義のメソッドをエラーにする設定」をオフにしました。

2023-05-30 06:54 UTC, zvvlj0219 commented
## ■FB修正分　確認依頼

### やったこと
- FB修正
- モデルにプロパティを追加し、エディター上の静的解析ができるよにした

2023-05-31 09:49 UTC, enes1004 approved these changes
修正確認できました！

お疲れ様です

2023-05-31 13:44 UTC, merged