【武井】学習報告 - 投稿詳細ページにて投稿されたコメントを表示させる、投稿できるようにする
StoryEdutech/study_repo pull request #58
Opened 2023-05-31 13:33 UTC by mokupon

# 内容

### 言語／フレームワーク
- Laravel
- React

### 勉強時間（※大体でOK）
5/28　2時間
5/29　3時間
5/31　1時間
(
投稿機能のコントローラー作成 - 30分
コメントをしたユーザー情報の取得と表示 - 30分
)

合計6時間

### 勉強内容

例：Controller作りました・データベースに接続を果たせました
- モデルの作成
- コメントをしたユーザー情報の取得と表示
- コメント投稿機能のコントローラー作成(取得,保存)

### 次勉強するもの
- nestの学習に入ります

# 感想
### 有用と思ったもの・意外だったもの
- withのネストで、「.」でつなぐことでその繋げたテーブル先からの情報も取得できるということ
※コメント情報を取ってきて、そのコメントのユーザー情報を取得する際に使いました

### 苦戦したもの
- inertiajsで用意しているuseFormの扱い

resolve #43
resolve #47

2023-06-01 14:24 UTC, mokupon commented on takei/blog/app/Models/Post.php
> +
#### ■相談
再度聞くことになること、申し訳ございません。

> fetchPostCommentsで抽象化してダメな理由

について再度理由を確認したいです。

武井が今回のコードを良しと思った背景として、
DBから情報を取ってくるということをコントローラーから切り離すことで、コントローラーの肥大を防ぐというものでした。
(もっというと、ビジネスロジックをモデルに持っていった)

だめな理由の予想としては、
今回の小規模開発において、無駄に切り離されているより、
コントローラーに書かれている方が可読性があがるせいが上がるからでしょうか、？

あらためて、再度聞くことになること、申し訳ございません。

2023-06-01 14:33 UTC, enes1004 commented on takei/blog/app/Models/Post.php
> +
大体あってます。Controllerを確認する人が、fetchPostCommentsを確認しないといけない、というのは良くない、ということです。また、太らせるといえば、Modelを太らせるのも良くないです。Modelから期待するのはRelationの定義やattributeの定義、Controllerから期待されるのはデータを取得して適切な形でJSONかViewを返す、と思ってください。

それでいうと、Model経由で取っている場合、データベースからの情報をControllerで取っても全然Okです。

ただ、複雑なロジックでデータを取る場合、Modelに入れるか、Controllerに入れるかはその都度考えるべきことです。

2023-06-02 03:35 UTC, mokupon commented
@enes1004 
@enes1004 
■相談
再度聞くことになること、申し訳ございません。

> 普段「タイトル・内容」と書くものがないので、デザインで切り分けて欲しい。

上記指摘の通り、デザインを変更済みです。
また、styled-componentsにしました。

styled-componentsにする必要のあるものか悩みましたが、
基本的に、styleを与える際はstyled-componentsにするべきという考えで、今回の対応を取りました。

https://github.com/StoryEdutech/study_repo/blob/ce53aef8d560f0c73adc3c1a870ddd07a27ac43f/takei/blog/resources/js/Pages/Posts/Show.jsx#L69-L75

https://github.com/StoryEdutech/study_repo/blob/ce53aef8d560f0c73adc3c1a870ddd07a27ac43f/takei/blog/resources/js/Pages/Posts/Show.jsx#L110-L113

2023-06-02 03:43 UTC, mokupon commented on takei/blog/app/Models/Post.php
> +
@enes1004 
ありがとうございます。モデルからコントローラーに戻し済みです。

1点確認です。
投稿詳細ページにて、投稿者の情報を$post変数に入れたく、
`$post = $post->load('user');`
のような対応を取りました。こちらの対応で問題なかったでしょうか？

https://github.com/StoryEdutech/study_repo/blob/ce53aef8d560f0c73adc3c1a870ddd07a27ac43f/takei/blog/app/Http/Controllers/PostController.php#L59-L64

https://github.com/StoryEdutech/study_repo/blob/ce53aef8d560f0c73adc3c1a870ddd07a27ac43f/takei/blog/app/Http/Controllers/PostController.php#L20-L24

2023-06-02 03:54 UTC, mokupon commented
> 一方、blogからpostにするのは正解です。前回の$postがIdだけになっていた理由もそれでしたので。[リンク](https://github.com/StoryEdutech/study_repo/pull/30#discussion_r1193166029)

ごめんなさい。こちらの背景がわかりませんでした。

今回の武井のでいうと、
js内でblogとした理由は、postという変数がuseFormですでに使われているため、別名にしたというものです。

解決方法として、
- js内でprops.postをblogにいれる
-コントローラーでblogという名前で渡す
という２種類あると思いますが、
フロントで
`const blog = props.post;`
または、
コントローラーで
`return Inertia::render('Posts/Show',['post' => $post, 'comments' => $comments]);`
どちらかになるというとき、コントローラーのほうが気持ち悪くなると思い、フロントで対応しました。

https://github.com/StoryEdutech/study_repo/blob/ce53aef8d560f0c73adc3c1a870ddd07a27ac43f/takei/blog/resources/js/Pages/Posts/Show.jsx#L33

2023-06-02 04:02 UTC, enes1004 commented
> styled-componentsにする必要のあるものか悩みましたが、 基本的に、styleを与える際はstyled-componentsにするべきという考えで、今回の対応を取りました。

このやり方、大有りです。むしろ、今後こうしてほしいぐらいです。スタイルの共通化なら、[共通のstyled-componentsを作って、拡張して](https://styled-components.com/docs/basics#extending-styles)もいい。むしろ、それでCSSファイルに`.button`など、ニッチなスタイルを過剰に入れる、というのが防げれます。

2023-06-02 04:13 UTC, enes1004 commented
```
今回の武井のでいうと、
js内でblogとした理由は、postという変数がuseFormですでに使われているため、別名にしたというものです。

```
その場合、useFormのpostを変えた方がいいと思います。前提としてpostを見れば「投稿」を思うので、post関数は命名として良くないです。おそらくHTTPのpostメソッドを使うからそういう命名なので、`postData`、`postRequest`などに変えても支障がないと思います。（requestしている、かつ、route()などでURIも受け取っているものなので、postRequestがいいかもしれません。）

ここ参照：
https://flaviocopes.com/how-to-rename-object-destructuring/

@zvvlj0219 上記記事の内容、知識として結構重要なので、確認を

2023-06-02 04:14 UTC, enes1004 requested changes

2023-06-02 05:14 UTC, mokupon commented
@enes1004 
> 他に使用/改造する予定がなければ、最初からrender/viewの中で定義してもいいです

ありがとうございます。上記に該当しているため、そちらで対応をしました。
https://github.com/StoryEdutech/study_repo/blob/66bd1c9c6f10cb3d5c4690831c4c86e0e3878609/takei/blog/app/Http/Controllers/PostController.php#L60-L63

また、コントローラーの他アクションも修正済みです。
https://github.com/StoryEdutech/study_repo/blob/66bd1c9c6f10cb3d5c4690831c4c86e0e3878609/takei/blog/app/Http/Controllers/PostController.php#L20-L92

2023-06-02 05:17 UTC, enes1004 approved these changes
一個だけBetter要件入れてますが、それ以外ばっちり！でマージOKです。

お疲れ様でした。

2023-06-02 05:17 UTC, enes1004 commented on takei/blog/app/Http/Controllers/PostController.php
> +        return Inertia::render('Posts/List',['posts' => Post::with('user')->get()]);
【ベター】
ここは改行した方が読みやすい。

2023-06-02 05:18 UTC, mokupon commented
@enes1004 
> その場合、useFormのpostを変えた方がいいと思います。前提としてpostを見れば「投稿」を思うので、post関数は命名として良くないです。おそらくHTTPのpostメソッドを使うからそういう命名なので、postData、postRequestなどに変えても支障がないと思います。（requestしている、かつ、route()などでURIも受け取っているものなので、postRequestがいいかもしれません。）

ありがとうございます。
こちら、postDataにすることで、blogをpostに戻し、修正済みです。
https://github.com/StoryEdutech/study_repo/pull/58/commits/eadb1c8cfbeab6eec4fc4e12c3d850292f2919ac

2023-06-02 05:27 UTC, mokupon commented on takei/blog/app/Http/Controllers/PostController.php
> +        return Inertia::render('Posts/List',['posts' => Post::with('user')->get()]);
改行の対応完了です。
https://github.com/StoryEdutech/study_repo/pull/58/commits/f1a3c46f50296623f11cc0c1c589e2ba5ce3614e

2023-06-02 05:27 UTC, mokupon commented
全ての修正が完了したので、マージします。
ありがとうございました！

2023-06-02 05:27 UTC, merged