【武井】 開発環境を整えて、最初のページを表示
StoryEdutech/study_repo pull request #63
Opened 2023-06-07 10:39 UTC by mokupon

# 内容

### 言語／フレームワーク
- Next

### 勉強時間（※大体でOK）

合計時間 5時間5分

- [記事](https://zenn.dev/azukiazusa/articles/next-js-app-dir-tutorial)をコピペでざっと一巡、学んだ所をメモで、計4時間
- CSR,SSR,SSG,ISRの学習で1時間
- 環境構築 5分

### 勉強内容

例：Controller作りました・データベースに接続を果たせました

-  CSR,SSR,SSG,ISRに付いての確認
-  [記事](https://zenn.dev/azukiazusa/articles/next-js-app-dir-tutorial)をコピペでざっと一巡
※学んだものはフォルダ直下にある「memo.md」に蓄積していきます

### 次勉強するもの
- Chakra UI を導入

# 感想
### 有用と思ったもの・意外だったもの

- react routerと比べて、ルーティングが格段に容易なこと。react routerでは定義をしていたが、nextはファイル構造によりルーティングが実現できる。

### 苦戦したもの
- ファイルシステムでのルーティングをもう少し理解を深めたい

### 楽しかったもの（※任意）
- [slug]フォルダを作成して、paramsを取得して、内容を表示するとき(reactだとgetから受け取りの処理をして,,,,という感じだったので楽で気持ち良い)

2023-06-07 11:27 UTC, mokupon commented
@enes1004 

■学習報告　1回目レビュー依頼

お手隙の際に確認をお願い致します。

2023-06-07 12:13 UTC, enes1004 approved these changes
メモに一部誤認あるので、それだけまた聞いたり・調べたりしてね。コードではないので、一旦Approveしておきます。

2023-06-08 05:17 UTC, mokupon commented on takei/next13_tutorial/app/globals.css
> +} */
@enes1004 
エネスさんの指摘通り、使ったほうが良さそうのため、復元しました。
https://github.com/StoryEdutech/study_repo/pull/63/commits/b1fc096f022643455dfefacbd208515b82e635d7

2023-06-08 06:01 UTC, mokupon commented on takei/next13_tutorial/memo.md
> +
@enes1004 
エネスさんからの指摘を受けて、理解したことを再整理をしました。

認識にズレがあったら、ご指摘いただけますと幸いです。
https://github.com/StoryEdutech/study_repo/pull/63/commits/806dd6ba5db94fa2e5591cbb9ec508daf0ef13f4

2023-06-08 07:55 UTC, mokupon commented
↑本当に申し訳ございません。完全に失念していて、chakraの導入もpushしてしまいました。

戻せるか確認します。

2023-06-08 08:15 UTC, enes1004 requested changes
他OKです～

Suggestionそのままコミットするなら、そのままマージしても構いません

2023-06-08 08:15 UTC, enes1004 commented on takei/next13_tutorial/memo.md
> +- コベツバではISR,CSRを採用する
「主に」です。そこがずれたら大変です
```suggestion
- コベツバでは主にISR,CSRを採用する
```

2023-06-08 09:08 UTC, mokupon commented on takei/next13_tutorial/memo.md
> +- コベツバではISR,CSRを採用する
ありがとうございます。
Suggestionそのままコミットするため、マージをします。

2023-06-08 09:09 UTC, merged