【木下】記事の詳細ページ
StoryEdutech/study_repo pull request #76
Opened 2023-06-15 06:49 UTC by zvvlj0219

# 内容

### 言語／フレームワーク
- Nextjs13

### 勉強時間（※大体でOK）

合計4時間
- api route コメント取得 2h?
- 他（関数切り出し、など）

### 勉強内容

例：Controller作りました・データベースに接続を果たせました

- 記事には、データを取得するapi routeの作成部分がなかったので、つくる（api はlaravelを使うことになるので、あんまり時間をかけたくなかったが、進められないので作りました）
- Streamingを使い、記事の詳細だけ先にレンダリングして、コメントは後からレンダリングされるようにした。
- generateMetadataで動的にtitle/descriptionを生成
- ※Chakra Uiでスタイリングはやってません

### 次勉強するもの
- 記事の生成（さらっと）

# 感想
### 有用と思ったもの・意外だったもの
- 動的にメタデータを作成できる機能、また親のページまで参照することができる

### 苦戦したもの
- api routeの書き方が、version12までと変わっていたこと

### 楽しかったもの（※任意）
- ストリーミングでレンダリングができること

2023-06-15 06:51 UTC, zvvlj0219 commented
## ■学習内容　レビュー依頼
@enes1004 
レビューを依頼します。お手すきの際に確認お願い致します。

2023-06-15 07:11 UTC, enes1004 approved these changes
問題なし！

2023-06-15 07:11 UTC, enes1004 commented on kinoshita/next-13-tutorial/blog-app/app/api/articles/[slug]/route.ts
> +    return article
```suggestion
const getArticlefromDummy = (slug:string): Article | undefined => {
    return articlesData.find(element => element.slug==slug)
```

2023-06-15 07:11 UTC, enes1004 commented on kinoshita/next-13-tutorial/blog-app/app/api/articles/route.ts
> +import articlesData from '@/dummy-data/articles.json'
Goodです！

ただ、fetchで使わないなら、.jsonより普通の.tsは書きやすいです。（Typeなどを定義して、さらにわかりやすくも出来ます。）

2023-06-15 07:11 UTC, enes1004 commented on kinoshita/next-13-tutorial/blog-app/dummy-data/articles.json
> +        "createdAt": "Wed Jun 14 2023 11:41:15 GMT+0900 (日本標準時)",
型としてちょっと変ですね。timestampか、datetimeに合わせて欲しいです。

2023-06-16 02:11 UTC, zvvlj0219 commented on kinoshita/next-13-tutorial/blog-app/dummy-data/articles.json
> +        "createdAt": "Wed Jun 14 2023 11:41:15 GMT+0900 (日本標準時)",
> 型としてちょっと変ですね。timestampか、datetimeに合わせて欲しいです。

mysqlのTIMESTAMP型かDATETIME型に合わせてほしい、という意図だと思い以下のように修正しました

[fb38d92](https://github.com/StoryEdutech/study_repo/pull/76/commits/fb38d920b7c657d2dc10efa31d361aa5d7465c27)

2023-06-16 02:11 UTC, zvvlj0219 commented on kinoshita/next-13-tutorial/blog-app/app/api/articles/route.ts
> +import articlesData from '@/dummy-data/articles.json'
tsファイルに変更しました

[fb38d92](https://github.com/StoryEdutech/study_repo/pull/76/commits/fb38d920b7c657d2dc10efa31d361aa5d7465c27)

2023-06-16 07:39 UTC, zvvlj0219 commented
@enes1004 

申し訳ございません。次の記事の作成ページの作業に入っていて、変更をこのPRにプッシュしてしまいました。
以下がそのコミットです。
[3274eb8](https://github.com/StoryEdutech/study_repo/pull/76/commits/3274eb84f42f53f824aa17c710b5d31f9aa5798c)

ローカル/リモートでpushした分を取り消そうとしていますが、うまくいっていません。記事をいくつか見ましたが、どのコマンドを実行するべきかの判断ができていません。
解決策をご教示いただけますと幸いです。、

■今試したこたとしたこと
```
git reset HEAD^
git pull 
```
の２つのコマンドです。

■ローカルの状況
ローカルではコミットが削除されています。
`git log`
をローカルで実行すると、コミットが消えています。(が、git pull したことで、変更していた分がstagingされている状態)

■リモートの状況
リモートでは、変更の履歴が残っています。

2023-06-16 07:58 UTC, enes1004 commented
pushしているならresetではなくrevertですね。

ただ、revertで編集分が全部消えるので、

一旦記事作成と同時に見ます。

記事作成も終わったらまた依頼出してください。

2023-06-16 08:04 UTC, zvvlj0219 commented
@enes1004 
承知いたしました。

> 記事作成も終わったらまた依頼出してください。

説明不足でした。記事作成まで完了しています。お手すきの際に確認お願い致します。

こちらのコミットになります。
[3274eb8](https://github.com/StoryEdutech/study_repo/pull/76/commits/3274eb84f42f53f824aa17c710b5d31f9aa5798c)

2023-06-16 11:02 UTC, enes1004 requested changes
記事作成も含めているならPR文章、修正してほしいです～　また、Issueへの紐付けも！

2023-06-16 11:02 UTC, enes1004 commented on kinoshita/next-13-tutorial/blog-app/dummy-data/comments.data.ts
> +] as Comment[]
as は極力使わない。

```suggestion
import { Comment } from "@/app/types"

const comments : Comment[] =  [
    {
        id: 1111,
        body: "コメント１",
        articleId: 1,
        createdAt: "2022-09-08 05:55:07",
        updatedAt: null,
        author: {
            "name": "",
            "avatarUrl": ""
        }
    },
    {
        id: 2222,
        body: "コメント2",
        articleId: 3,
        createdAt: "2019-09-08 05:55:07",
        updatedAt: null,
        author: {
            "name": "",
            "avatarUrl": ""
        }
    }
];

export default comments;
```

2023-06-18 09:18 UTC, zvvlj0219 commented on kinoshita/next-13-tutorial/blog-app/dummy-data/comments.data.ts
> +] as Comment[]
こちらで修正しました。

[a60f7ca](https://github.com/StoryEdutech/study_repo/pull/76/commits/a60f7ca5ae9614f075aec832c8e5dc24517c95b4)

2023-06-18 09:29 UTC, zvvlj0219 commented on kinoshita/next-13-tutorial/blog-app/app/articles/[slug]/_helper/index.ts
> +export { getComments } from "./getComments"
@enes1004 
コンポーネントで呼び出すときに、参照先をindex.tsにまとめたいという意図がありました。

まとめた場合
```
import { getArticle, getComments } from './_helper'
````

まとめなかった場合
```
import { getArticle } from './_helper/getArticle'
import { getComments } from './_helper/getComments'
```

2023-06-18 09:32 UTC, zvvlj0219 commented on kinoshita/next-13-tutorial/blog-app/app/articles/[slug]/page.tsx
> +    const comments = await getComments(articleId)
こちらで修正しました
[fffeb1e](https://github.com/StoryEdutech/study_repo/pull/76/commits/fffeb1e89eb8b217a4b8c92ce1ffd57e544da1ae)

2023-06-18 09:32 UTC, zvvlj0219 commented on kinoshita/next-13-tutorial/blog-app/app/articles/[slug]/page.tsx
> +            </Suspense>
こちらで修正しました
[fffeb1e](https://github.com/StoryEdutech/study_repo/pull/76/commits/fffeb1e89eb8b217a4b8c92ce1ffd57e544da1ae)

2023-06-18 09:32 UTC, zvvlj0219 commented on kinoshita/next-13-tutorial/blog-app/app/articles/[slug]/page.tsx
> +    const article = await getArticle(slug)
こちらで修正しました
[fffeb1e](https://github.com/StoryEdutech/study_repo/pull/76/commits/fffeb1e89eb8b217a4b8c92ce1ffd57e544da1ae)

2023-06-18 09:32 UTC, zvvlj0219 commented on kinoshita/next-13-tutorial/blog-app/app/articles/[slug]/loading.tsx
> +    return <h1>!!記事の詳細を取得中です...!!</h1>
こちらで修正しました
[fffeb1e](https://github.com/StoryEdutech/study_repo/pull/76/commits/fffeb1e89eb8b217a4b8c92ce1ffd57e544da1ae)

2023-06-18 09:32 UTC, zvvlj0219 commented on kinoshita/next-13-tutorial/blog-app/app/articles/[slug]/_helper/index.ts
> +export { getArticle } from "./getArtilce"
こちらで修正しました
[fffeb1e](https://github.com/StoryEdutech/study_repo/pull/76/commits/fffeb1e89eb8b217a4b8c92ce1ffd57e544da1ae)

2023-06-18 10:24 UTC, zvvlj0219 commented on kinoshita/next-13-tutorial/blog-app/app/articles/[slug]/page.tsx
> +    )
こちらで修正しました
[6d50c3c](https://github.com/StoryEdutech/study_repo/pull/76/commits/6d50c3c496d6e4b4c5327c28acc2620b52f6abe9)

2023-06-18 13:42 UTC, enes1004 commented on kinoshita/next-13-tutorial/blog-app/app/articles/[slug]/_helper/index.ts
> +export { getComments } from "./getComments"
大した差がないような :thinking: 

逆に、このコードを見て、getArticleを見たい人が、まずindexに飛んでからgetArticleに飛ぶことになりそう。

helperんp数が増えたらhelper/index.tsにも登録していく、ということになって、管理コストもかかりそう

2023-06-18 13:44 UTC, enes1004 approved these changes
お疲れさまでした！

2023-06-19 01:10 UTC, zvvlj0219 commented on kinoshita/next-13-tutorial/blog-app/app/articles/[slug]/_helper/index.ts
> +export { getComments } from "./getComments"
理解しました。デメリットのほうが大きそうと分かりました。

[beb7da8](https://github.com/StoryEdutech/study_repo/pull/76/commits/beb7da8e4206935f74232fd4b5dd85a2a2f87111)

2023-06-19 09:32 UTC, merged