【武井】記事の詳細ページ & 記事作成ページ
StoryEdutech/study_repo pull request #79
Opened 2023-06-20 05:28 UTC by mokupon

# 内容

### 言語／フレームワーク
-  next

### 勉強時間（※大体でOK）

合計5時間

### 勉強内容

- ストリーミングでのコメント取得(<Suspense>を利用)
  - 全ての読み込みが終わってから表示でなく、読み終えているものから表示させるための対応

### 次勉強するもの
- ドキュメントの読み込み,chatgptの活用

# 感想
### 有用と思ったもの・意外だったもの
- <Suspense>について 

### 苦戦したもの
- type scriptの扱い

### 楽しかったもの（※任意）
- コメントの表示

2023-06-22 06:35 UTC, mokupon commented
@enes1004 
確認依頼が遅くなってしまったこと、申し訳ございません。
お手隙の際にご確認いただけますと、さいわいです。

今回、木下さんのFBにてあった、ダミーデータを.tsにして対応するということはしていませんが、
その他はできていると思っています。

2023-06-22 09:32 UTC, enes1004 requested changes
typescript、苦戦してますね  :mechanic:   :sweat_drops:

2023-06-22 09:32 UTC, enes1004 commented on takei/next13_tutorial/app/page.tsx
> +  return data as Article[];
as は基本的に使わないように！
```
const data: Article[] = await res.json();
return data;
```

2023-06-22 09:32 UTC, enes1004 commented on takei/next13_tutorial/app/articles/[slug]/page.tsx
> +        <Comments commentPromise={commentPromise} />
？？？
Promiseじゃなくてもいけるはずだと思うけどね。Promiseは逆にいつもtrue扱いだから、ifなどが入ったら大変になる。開発でまた遭遇したらその時見せてください。

2023-06-22 09:32 UTC, enes1004 commented on takei/next13_tutorial/app/articles/[slug]/page.tsx
> +        <Comments commentPromise={commentPromise} />
なんなら、getCommentsをCommentsの中で呼んだ方が綺麗と思う方です。

2023-06-22 09:32 UTC, enes1004 commented on takei/next13_tutorial/pages/api/articles/index.ts
> +    articles.sort((a: any, b: any) => {
型は`Article`のはずです。書いておいた方がdebugしやすいです。（逆に一個上で`articles:Article[]`があればanyが不要に成りそうな気がします。）

2023-06-25 02:23 UTC, mokupon commented on takei/next13_tutorial/pages/api/articles/index.ts
> +    articles.sort((a: any, b: any) => {
@enes1004 

ありがとうございます。下記コミットの通り、修正済みです。
https://github.com/StoryEdutech/study_repo/pull/79/commits/d2587e6f06cf300720b5ac79e232b83eb8905680

2023-06-25 02:26 UTC, mokupon commented on takei/next13_tutorial/app/page.tsx
> +  return data as Article[];
@enes1004 
ありがとうございます、！以後気をつけます。

下記のコミットの通り、対応済みです
https://github.com/StoryEdutech/study_repo/pull/79/commits/3fec2b78f3933fb079f9d23dd000f95d213a3ebd#diff-8fe9909acbb9796ce24a952a24a1d7a569e83e607080bb518a480321dbe6724fL13-L15

2023-06-25 10:37 UTC, mokupon commented on takei/next13_tutorial/app/articles/[slug]/page.tsx
> +        <Comments commentPromise={commentPromise} />
@enes1004 

> なんなら、getCommentsをCommentsの中で呼んだ方が綺麗と思う方です。

ありがとうございます。
こちら、Commentsの中に対して、params.flugを渡すことで、対応をしてみました。

getCommentsに対しての戻り値の型を追加しましたが、関数の定義時に戻り値の型も記載するべきでしょうか、？

returnする変数に対して型が書いてあれば、そこで戻り値の型を理解できると思いますが、
型を書けるところは徹底的に書くのか、エラーが起きない程度に書けば良いのかがわからず、
質問させていただきました。

https://github.com/StoryEdutech/study_repo/pull/79/files/0bd8d2f63f62e497c7f727bf7f6ccc93d893fd39..36d521084fa776344e1f6a322d365e4a59085010

2023-06-26 02:42 UTC, enes1004 commented on takei/next13_tutorial/app/articles/[slug]/page.tsx
> +        <Comments commentPromise={commentPromise} />
```
getCommentsに対しての戻り値の型を追加しましたが、関数の定義時に戻り値の型も記載するべきでしょうか、？
```
双方必要です。

- 関数の定義時に戻り値の型： getCommentsを使う時のバリデーションが出来る
- 取得した時の返り値の記載：（書いた本人も含めて）コードを読む人がgetCommentsの詳細を見ずともcommentsがどういうものか分かる、その後のバリデーションが楽

ということです。

> returnする変数に対して型が書いてあれば、そこで戻り値の型を理解できると思いますが、
> 型を書けるところは徹底的に書くのか、エラーが起きない程度に書けば良いのかがわからず、
> 質問させていただきました。

書かなさすぎより書きすぎがベターなので、迷うなら書いてください。

ただ、

- 関数定義時
- 関数を使用して返ったもの（＝ぱっと見で方が分からないもの）

は基本的に書くようにしましょう

2023-06-26 02:43 UTC, enes1004 approved these changes

2023-06-26 05:58 UTC, mokupon commented on takei/next13_tutorial/app/articles/[slug]/page.tsx
> +        <Comments commentPromise={commentPromise} />
@enes1004 
ありがとうございます。

> 書かなさすぎより書きすぎがベターなので、迷うなら書いてください。
> 関数定義時
関数を使用して返ったもの（＝ぱっと見で方が分からないもの）
は基本的に書くようにしましょう

上記、承知しました。

下記コミットのとおりで、修正済みです。
https://github.com/StoryEdutech/study_repo/pull/79/commits/b9f5ff5846aef516c9b2ba5e559379ab89e9cc9c

2023-06-26 06:44 UTC, mokupon commented
対面でマージおｋということだったため、マージさせていただきます。
FBいただき、本当にありがとうございました、！

2023-06-26 06:44 UTC, merged