Yamanaka study
StoryEdutech/study_repo pull request #85
Opened 2023-10-31 10:38 UTC by yamanga

# 内容

### 言語／フレームワーク
- Laravel
- Next.js

### 勉強時間（※大体でOK）

合計5.5時間

### 勉強内容

- LaravelでAPIを作成
  - PHPとcomposerのインストール
  - Laravelプロジェクトの作成
  - Laravel breezeのインストール
  - sqliteの設定
  - Article,Commentのmigration,model,controller,resource,factoryファイルを作成
  - チュートリアルで利用したget(api/articles),get(api/articles/slug),get(api/articles/slug/comments),post(api/articles)まで作成
  - AppServiceProviderのbootに`JsonResource::withoutWrapping()`を追記することでdataキーによるラップを無効にした
  - seederの設定
- Next.jsでのfetchのURLを変えた
- POSTを行うと419エラーが発生、csrfトークン関連のエラーらしい

### 次勉強するもの

- 419エラーの解消
- 記事作成失敗時の表示を追加
- コメント追加機能を追加
- フィードバックに基づく修正

# 感想
### 有用と思ったもの・意外だったもの

- factoryでリレーションを設定しながらテストデータを作成する方法を知った。
- sqliteは設定不要で簡単に利用でき、便利だと思った。

2023-11-01 14:15 UTC, yamanga commented
# 内容

### 言語／フレームワーク
- Laravel
- Next.js

### 勉強時間（※大体でOK）

合計9時間

### 勉強内容

- LaravelでAPIを作成
  - 419エラーの解消
    - まずはget(sanctum/csrf-cookie)を行うことでcsrfトークンを入手した
    - Cookieから特定のキーの値を取得する関数を作成し、POSTする際にX-XSRF-TOKENヘッダーにその値を入れた
      - まず、cookie全体の文字列を"; "でsplitしてforeachでkeyが一致すれば値を返し、見つからなければ空文字を返すように実装したが、毎回空文字が返る。→　async/awaitを用いて処理を待つことでうまく動作するようにした
      - しかし、まだ419エラーが発生する。Logを用いて調べたところ、トークンの複合の際、Decrypt Exceptionが発生していることが判明　→　キーの値にdecodeURIComponent()を使うことで解消。値の中に=があり、エンコードされて値が変化していた
  - APIが記事の集合を返す時にArticleResourceの形式が反映されていなかったのを修正
  - articlesは更新が新しい順、commentsは登録が新しい順に並べてAPIから返すように変更
  - ArticleのModelのfillableにslugを追加、CommentのModelのfillableにarticle_idを追加し、正常にcreateできるようにした
  - コメント送信フォームとコメント送信用のAPIを作成
  - POSTを実行した後、レスポンスに応じて、失敗したことを表示するようにした
    - 最初、ヘッダーのAcceptにapplication/jsonを設定していなかったため、失敗した際、htmlが返ってきていた

### 次勉強するもの

- フィードバックに基づく修正


# 感想
### 苦戦したもの

- 最初、419エラーを解消するためにどうすればいいかにたどり着くのに時間がかかった。その後も、トークンをデコードする必要があることに気づくのに時間がかかった。

2023-11-02 03:11 UTC, enes1004 requested changes
お疲れさまです！

かなり進んでましたね！

いくつか気になる点があるので、確認してください。

2023-11-02 03:11 UTC, enes1004 commented on yamanaka/nextjs-app-dir/app/articles/[slug]/page.tsx
>          <Comments commentPromise={commentPromise} />
`Comments`もServerComponentなので、slugだけをパスして、データは`Comments`で取得した方がいいと思います。

背景は、以下二つ

- データの取得を`Comments`に書いた方が、見通しがいい。コメントだけに関わる変化があった時にこのファイルをを見るより、`Comments`をみた方が多いと思うので。
- `@ts-expect-error`は可能な限りなくしたい。せっかくエラーを減らすtypescriptなのに、例外対応を増えすぎたらその価値が薄くなってしまいそうです。

2023-11-02 03:11 UTC, enes1004 commented on yamanaka/nextjs-app-dir/app/page.tsx
> +  const res = await fetch("http://localhost:8000/api/articles", {
`http://localhost:8000/`の部分、定数にしてみませんか？

このレポをリリースした時に定数一つを変えるだけで済むし、その定数を`process.env`から取得するようにしたら、環境に依存せず、APIを切り替えられます。

(laravel側で`FRONTEND_URL`を定義するのと似たような感じです。)

2023-11-02 03:11 UTC, enes1004 commented on yamanaka/laravel/database/migrations/2023_10_31_074535_create_comments_table.php
> +            $table->string('avater_url');
この二つのカラムは何でしょうか？

ユーザーの名前とアバターだったりしませんか？

それでしたら、ここよりusersに追加すべきだと思います。

2023-11-02 03:11 UTC, enes1004 commented on yamanaka/laravel/app/Models/Article.php
> +}
投稿者のUserとの関係性がなくていいですか？

2023-11-02 03:11 UTC, enes1004 commented on yamanaka/laravel/app/Models/Comment.php
> +}
投稿者のUserとの関係性がなくていいですか？

2023-11-03 14:12 UTC, yamanga commented on yamanaka/nextjs-app-dir/app/articles/[slug]/_components/SendComment.tsx
> +      );
Axiosのv1.6.0では、脆弱性解消のため自動で対応しないようになっていました。古いバージョンを使って自動で行ってもらいました。

2023-11-06 13:51 UTC, yamanga commented
# 内容

### 言語／フレームワーク
- Laravel
- Next.js

### 勉強時間（※大体でOK）

合計8時間

### 勉強内容

- LaravelでAPIを作成
- ログインページと新規登録ページの作成
- ログイン時のみ記事作成とコメント送信ができるようにした
- コメント送信は内容のみを入力させるようにする
  - これに伴い、ユーザーとコメントのlaravel側の処理やシーダー
- ログイン時、ログアウトボタンを表示
- login、userコンテクストの導入
  - 導入前はログインしているか判定が必要になる度にapi/userを叩いていた
  - 今後ユーザーデータの変更を行う際やマイページを作ることを考え、userコンテクストも作成したが、まだ使用していない

### 次勉強するもの

- フィードバックに基づく修正


# 感想
### 苦戦したもの

- 最初、ログインしているかどうかをどう判定するかでかなり迷った。最初は判定が必要になる度にログイン状態でないと失敗するapiを叩き、その反応で判定することで実装した。その後、コンテクストを用いて、初回レンダー時にapiを叩いてログインしているかどうかを保持し、あとは認証が必要なapiを叩いた際に更新するようにした。

2023-11-07 04:08 UTC, enes1004 approved these changes
課題、お疲れさまでした！

実際動かしてみても、使い勝手良さそうでした！

コードに関していくつかベター要件を出してますが、確認・返信だけで大丈夫です！修正はしなくてOkです。

後、認証あたりでかなり苦戦していた様子でしたね。ログイン/登録がかなり一般的なので、こちらに関しては、ライブラリーがないか？サンプルはないか？を先に考えて欲しかったです。

もちろん、結果的に機能しているものが作っている、調査/試行錯誤できて、いい勉強になってたと思いますよ！

ただ、仕事の場では、無闇に実装に入るより、目的に対しての適切な方法を先に考えることがかなり大事です。それによって、適切な形でなるべき速く実装する、それでユーザー・組織の価値につながることが出来ます。なので、

**「自分が把握している手段でどう解決するか？」ではなく、「目的は何？それに対して一番適切な手段は？」**

というところから考え始めましょう。

もちろん、その結果、場合によってライブラリーを入れることもあれば、むしろ、自分で一から実装するものもあります。

＝＝＝＝

※ 今回でいうと、実は、[Breezeの公式資料にNextのサンプル](https://laravel.com/docs/10.x/starter-kits#next-reference-implementation)のリンクがあって、それを見つけて参考に出来たらいいなと思ってました。サンプル自体、古いpagesルーターを使ってますが、本質的に対応する内容がほぼので、参考に出来たと思います。

2023-11-07 04:45 UTC, merged